### ISSUE TITLE
Storyオブジェクトのpropsに型をつける

### ISSUE THREAD

**Issue by fumiharun11** [daily-fishmonger/project_yamame#38]
[参考記事](https://qiita.com/kahirokunn/items/5086a026c4d4a5b61e69)

**Comment by nisshii0313** [comment]
https://github.com/daily-fishmonger/project_yamame/pull/36#discussion_r593836434

componentのprops自体に型をつけるよりかはstorybookのpropsとしての型をつけた方が良いのかも...
``` 
export interface Props {
  label: string;
  color: string;
  size: 'small' | 'medium';
}
```
みたいな感じ (もっと必要かも？？)

追伸：
props定義の時にvalidatorを使うとdefineComponentの型推論が効かなくなるので、validatorを使わずに型定義で例外を弾きたいというお気持ちもある

**Comment by nisshii0313** [comment]
今、何も考えずに`src/components/atoms/story.d.ts`って置いちゃってるんだけど、冷静に考えたら`src/components/story.d.ts`で置く方が正しそうなので、その時になったら適当に変更してくださいまし 🙏 

→ Moleculesな方の型付けに影響しそうなので、これだけ自分の方で直しておきますん！
