### ISSUE TITLE
弾幕の軌跡ロジックの実装

### ISSUE THREAD

**Issue by ayakotanaka0224** [daily-fishmonger/project_yamame#4]
- サイクロイド
- アステロイド曲線
- カージオイド曲線
- 対数螺旋
- リサージュ図形
- レムニスケート
- インボリュート曲線

https://mathtrain.jp/sevencurve

**Comment by fumiharun11** [comment]
ダミーオブジェクトのサイズ: 50px 25px

**Comment by fumiharun11** [comment]
進捗共有
![moveCat](https://user-images.githubusercontent.com/28529274/118389970-87bb0700-b667-11eb-88b8-18eb446ef365.gif)

**Comment by nisshii0313** [comment]
案１： 固定値
おじさん: {
　PC: {
　　身長: 334,
　　腹囲: 166,
　},
　SP: {
　　身長: 167,
　　腹囲: 83,
　}
}

案２：パーセント (縦長モニターとか心配)
