### ISSUE TITLE
開発環境にpre-commitルールを作成する

### ISSUE THREAD

**Issue by ayakotanaka0224** [daily-fishmonger/project_yamame#5]
[開発指針](https://github.com/daily-fishmonger/project_yamame/wiki/%E9%96%8B%E7%99%BA%E6%8C%87%E9%87%9D)

## 備考
- `pre-commit`を有効にする為の設定を書く

**Comment by ayakotanaka0224** [comment]
`editorconfig`と`eslintrc.json`は @nisshii0313 に準備して頂く

**Comment by fumiharun11** [comment]
`pre-commit`の設定に[yorkie](https://www.npmjs.com/package/yorkie)ではなく[husky](https://www.npmjs.com/package/husky)を使用したかったが, 想定している動作が行われなかったことに加えて`@vue/cli-service`にはyorkieが含まれているので一時的に[VueCLIのドキュメント](https://cli.vuejs.org/guide/cli-service.html#git-hooks)に沿うことにした.

**Comment by fumiharun11** [comment]
`lint-staged`を`package.json`に追加し忘れたのでReopen
