### ISSUE TITLE
[Atoms]timerコンポーネントの作成

### ISSUE THREAD

**Issue by fumiharun11** [daily-fishmonger/project_yamame#9]
## 何を作るか
PLAYING画面に表示するタイマーの作成

## 画像

![default](https://user-images.githubusercontent.com/28529274/108713153-2c431680-755b-11eb-9ea9-89825f8c4814.png)

![half](https://user-images.githubusercontent.com/28529274/108713224-43820400-755b-11eb-97a9-39b1f4110c17.png)

![quarter](https://user-images.githubusercontent.com/28529274/108713228-45e45e00-755b-11eb-9283-f0d3bef0c02c.png)

![up](https://user-images.githubusercontent.com/28529274/108713239-48df4e80-755b-11eb-9a37-02e8b876c435.png)

## Figma URL
https://www.figma.com/file/Lb7iiT1OPlVsYEuZU0w2AD/?node-id=11%3A26

**Comment by ayakotanaka0224** [comment]
https://css-tricks.com/building-progress-ring-quickly/
